version: "3.8"

services:
  # Database service
  postgres:
    image: postgres:15
    container_name: library_postgres
    restart: always
    environment:
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_password
      POSTGRES_DB: library_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-data/sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - library_network

  # Spring Boot application service
  app:
    build: .
    container_name: library_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/library_db
      SPRING_DATASOURCE_USERNAME: library_user
      SPRING_DATASOURCE_PASSWORD: library_password
    depends_on:
      - postgres
    networks:
      - library_network

volumes:
  postgres_data:

networks:
  library_network:
    driver: bridge
